src/Entity/Album.php
<?php

namespace App\Entity;

use App\Repository\AlbumRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AlbumRepository::class)]
class Album
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $illustrationURL = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $releaseDate = null;

    #[ORM\OneToMany(mappedBy: 'album', targetEntity: Music::class, orphanRemoval: true)]
    private Collection $musics;

    #[ORM\ManyToOne(inversedBy: 'albums')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Artist $artist = null;

    public function __construct()
    {
        $this->musics = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getIllustrationURL(): ?string
    {
        return $this->illustrationURL;
    }

    public function setIllustrationURL(string $illustrationURL): self
    {
        $this->illustrationURL = $illustrationURL;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->releaseDate;
    }

    public function setReleaseDate(\DateTimeInterface $releaseDate): self
    {
        $this->releaseDate = $releaseDate;

        return $this;
    }

    /**
     * @return Collection<int, Music>
     */
    public function getMusics(): Collection
    {
        return $this->musics;
    }

    public function addMusic(Music $music): self
    {
        if (!$this->musics->contains($music)) {
            $this->musics->add($music);
            $music->setAlbum($this);
        }

        return $this;
    }

    public function removeMusic(Music $music): self
    {
        if ($this->musics->removeElement($music)) {
            // set the owning side to null (unless already changed)
            if ($music->getAlbum() === $this) {
                $music->setAlbum(null);
            }
        }

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }
}

src/Entity/Music.php
<?php

namespace App\Entity;

use App\Repository\MusicRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MusicRepository::class)]
class Music
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\ManyToOne(inversedBy: 'musics')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Album $album = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function getHumanReadableDuration(): string
    {
        $seconds = $this->getDuration();
        $hours = floor($seconds / 3600);
        $minutes = floor(($seconds / 60) % 60);
        $seconds = $seconds % 60;

        $duration = '';

        if ($hours) {
            $duration .= "$hours:";

            if ($minutes < 10) {
                $minutes = "0$minutes";
            }
        }

        if ($seconds < 10) {
            $seconds = "0$seconds";
        }

        $duration .= "$minutes:$seconds";

        return $duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): self
    {
        $this->album = $album;

        return $this;
    }
}

src/Controller/AlbumController.php
<?php

namespace App\Controller;

use App\Entity\Album;
use App\Repository\AlbumRepository;
use App\Repository\ArtistRepository;
use DateTime;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AlbumController extends AbstractController
{
    #[Route('/albums', name: 'show_albums')]
    public function index(AlbumRepository $albumRepository): Response
    {
        // Récupération de tous les albums
        $albums = $albumRepository->findAll();

        // Affichage de la page avec les albums
        return $this->render('album/index.html.twig', [
            'albums' => $albums,
        ]);
    }

    #[Route('/albums/new', name: 'new_album', methods: ['GET', 'POST'])]
    public function add(Request $request, ManagerRegistry $doctrine, ArtistRepository $artistRepository): Response
    {
        // Récupération du gestionnaire d'entités
        $entityManager = $doctrine->getManager();

        // Récupération de l'unique artiste
        $artist = $artistRepository->find(1);

        if ($request->getMethod() === 'POST') {
            // Si l'artiste n'existe pas encore, on ne peut pas ajouter d'album
            if ($artist === null) {
                throw $this->createAccessDeniedException('Vous devez d\'abord ajouter un artiste');
            }

            //Création du nouvel album
            $album = new Album();

            $album->setTitle($request->request->get('title'))
                ->setIllustrationURL($request->request->get('illustrationURL'))
                ->setReleaseDate(new DateTime($request->request->get('releaseDate')))
                ->setArtist($artist);

            // On précise à Doctrine qu'il va falloir l'enregistrer
            $entityManager->persist($album);

            // Exécute toutes les requêtes SQL en attente
            $entityManager->flush();

            // On redirige vers la liste des albums
            return $this->redirectToRoute('show_albums');
        }

        // Si méthode GET, on affiche le formulaire d'ajout de l'album
        return $this->render('album/new.html.twig', [
            'artist' => $artist,
        ]);
    }

    #[Route('/albums/{id}', name: 'show_album')]
    public function show(Album $album): Response
    {
        // L'album est auto-injecté dans $album parce qu'il y a l'ID dans la route
        return $this->render('album/show.html.twig', [
            'album' => $album,
        ]);
    }

    #[Route('/albums/{id}/edit', methods: ['GET', 'POST'], name: 'edit_album')]
    public function edit(Request $request, Album $album, ManagerRegistry $doctrine): Response
    {
        // Si on poste depuis le formulaire
        if ($request->getMethod() === 'POST') {
            // Récupération du gestionnaire d'entités
            $entityManager = $doctrine->getManager();

            $album
                ->setTitle($request->request->get('title'))
                ->setIllustrationURL($request->request->get('illustrationURL'))
                ->setReleaseDate(new DateTime($request->request->get('releaseDate')));

            // Exécute toutes les requêtes SQL en attente
            $entityManager->flush();
            return $this->redirectToRoute('show_album', ['id' => $album->getId()]);
        }

        // Si méthode GET, on affiche le formulaire d'ajout de l'album
        return $this->render('album/edit.html.twig', [
            'album' => $album,
        ]);
    }
}

templates/album/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modifier l'album {{ album.title }}{% endblock title %}

{% block body %}
  <h1>Mettre à jour un album</h1>

  <form
    action="{{ path('edit_album', {id: album.id}) }}"
    method="post"
    class="mx-auto"
    style="max-width: 30rem;"
  >
    <div class="mb-3">
      <label for="title">Titre</label>
      <input
        type="text"
        value="{{ album.title|default('') }}"
        name="title"
        id="title"
        class="form-control"
        placeholder="Titre"
      >
    </div>
    <div class="mb-3">
      <label for="illustrationURL">Illustration</label>
      <input
        type="text"
        value="{{ album.illustrationURL|default('') }}"
        name="illustrationURL"
        id="illustrationURL"
        class="form-control"
        placeholder="URL de l'illustration"
      >
    </div>
    <div class="mb-3">
      <label for="releaseDate">Date de sortie</label>
      <input
        type="date"
        value="{{ album.releaseDate|default('now')|date("Y-m-d") }}"
        name="releaseDate"
        id="releaseDate"
        class="form-control"
        placeholder="Date de sortie"
      >
    </div>
    <div class="text-end">
      <button type="submit" class="btn btn-primary">
        <i class="fa-solid fa-save"></i>
        Mettre à jour
      </button>
    </div>
  </form>
{% endblock body %}

templates/album/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des albums{% endblock title %}

{% block body %}
  <div class="mb-3">
    <a class="btn btn-primary" href="{{ path('new_album') }}">
      <i class="fa-solid fa-plus"></i>
      Ajouter
    </a>
  </div>

  {% if albums|length == 0 %}
    <div class="alert alert-warning" role="alert">
      Il n'y a pas encore d'album.
    </div>
  {% else %}
    <div class="row row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-col-lg-5">
      {% for album in albums %}
        <div class="col">
          <div class="card">
            <img src="{{ album.illustrationURL }}" alt="{{ album.title }} cover" class="card-img-top">
            <div class="card-body">
              <h5 class="card-title">{{ album.title }}</h5>
              <p class="card-text">
                Album sorti le {{ album.releaseDate|date("d/m/Y") }}
              </p>
              <a href="{{ path('show_album', {id: album.id}) }}" class="stretched-link text-decoration-none">
                <i class="fa-solid fa-eye"></i>
                Voir plus
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

templates/album/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Ajouter un album{% endblock title %}

{% block body %}
  <h1>Ajouter un album</h1>

  {% if artist is null %}
    <div class="alert alert-warning" role="alert">
      Vous devez d'abord créer un artist avant de pouvoir ajouter un album.
    </div>
  {% endif %}

  <form
    action="{{ path('new_album') }}"
    method="post"
    class="mx-auto"
    style="max-width: 30rem;"
  >
    <div class="mb-3">
      <label for="title">Titre</label>
      <input
        type="text"
        name="title"
        id="title"
        class="form-control"
        placeholder="Titre"
      >
    </div>
    <div class="mb-3">
      <label for="illustrationURL">Illustration</label>
      <input
        type="text"
        name="illustrationURL"
        id="illustrationURL"
        class="form-control"
        placeholder="URL de l'illustration"
      >
    </div>
    <div class="mb-3">
      <label for="releaseDate">Date de sortie</label>
      <input
        type="date"
        name="releaseDate"
        id="releaseDate"
        class="form-control"
        placeholder="Date de sortie"
      >
    </div>
    <div class="text-end">
      <button type="submit" class="btn btn-primary">
        <i class="fa-solid fa-plus"></i>
        Ajouter
      </button>
    </div>
  </form>
{% endblock body %}

templates/album/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Détail de l'album {{ album.title }}{% endblock title %}

{% block body %}
  <div class="row">
    <div class="col-sm-3">
      <img src="{{ album.illustrationURL }}" alt="{{ album.title }} cover" class="img-fluid rounded shadow mb-2">
      <p class="text-secondary">Album sorti le {{ album.releaseDate|date("d/m/Y") }}.</p>
    </div>
    <div class="col-sm-9">
      <h2 class="fw-bold row align-items-center">
        {# Le titre de l'album #}
        <div class="col">
          {{ album.title }}
        </div>

        {# Le menu pour éditer l'album #}
        <div class="col-auto">
          <div class="dropdown">
            <a href="#" class="text-danger rounded-pill" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-ellipsis fa-fw"></i>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{{ path('edit_album', {id: album.id}) }}">
                  <i class="fa-solid fa-pen-to-square fa-fw"></i>
                  Éditer l'album
                </a>
              </li>
            </ul>
          </div>
        </div>
      </h2>

      <div class="mb-2">
        <button class="btn btn-danger mb-1">
          <i class="fa-solid fa-play"></i>
          Lecture
        </button>
        <button class="btn btn-danger mb-1">
          <i class="fa-solid fa-shuffle"></i>
          Ordre aléatoire
        </button>
        <a class="btn btn-secondary mb-1" href="{{ path('add_music', {id: album.id}) }}">
          <i class="fa-solid fa-plus"></i>
          Ajouter un morceau
        </a>
      </div>

      {% if album.musics|length != 0 %}
        <ul class="list-unstyled music-list container-fluid">
          {% for music in album.musics %}
            <li class="row music-item py-1 rounded position-relative" style="min-width: 0;">
              {# L'index de la musique dans l'album #}
              <div class="col-auto text-end px-0" style="width: 2rem;">{{ loop.index }}</div>

              {# Le titre de la musique #}
              <div class="col text-truncate ms-2">{{ music.title }}</div>

              {# La durée lisible par un humain #}
              <div class="col-auto">{{ music.humanReadableDuration }}</div>

              {# Le menu pour éditer la musique #}
              <div class="col-auto">
                <div class="dropdown">
                  <a href="#" class="text-danger rounded-pill" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-ellipsis fa-fw" data-fa-transform="grow-5"></i>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="{{ path('edit_music', {id: music.id}) }}">
                        <i class="fa-solid fa-pen-to-square fa-fw"></i>
                        Éditer le morceau
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p class="text-secondary">Il n'y a aucune musique.</p>
      {% endif %}
    </div>
  </div>
{% endblock body %}